# Generated by Django 3.2.6 on 2022-09-03 23:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AutoUser', '0002_alter_autouser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='autouser',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='default_profile_pic', upload_to='photos/autouser/'),
        ),
    ]
