# Generated by Django 3.2.6 on 2022-09-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoUser', '0007_alter_autouser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autouser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
