# Generated by Django 3.2.6 on 2022-09-07 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoUser', '0008_alter_autouser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('auto_user', models.ManyToManyField(blank=True, related_name='autouserfavourite', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ManyToManyField(blank=True, related_name='technicianfavourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
