# Generated by Django 3.2.6 on 2022-09-03 23:59

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopfeedbackrating',
            old_name='technician_id',
            new_name='technician',
        ),
        migrations.RenameField(
            model_name='techniciandetails',
            old_name='autouser_id',
            new_name='autouser',
        ),
        migrations.RenameField(
            model_name='technicinanbadge',
            old_name='technician_id',
            new_name='technician',
        ),
        migrations.AlterField(
            model_name='techniciandetails',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(default='default_technician_photo', upload_to='photos/autouser/'),
        ),
    ]
