# Generated by Django 3.2.6 on 2022-09-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_auto_20220903_2359'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicinanBadge',
            new_name='TechnicianBadge',
        ),
        migrations.RenameModel(
            old_name='TechnicianSpecializaitons',
            new_name='TechnicianSpecializations',
        ),
    ]
