# Generated by Django 3.2.6 on 2022-09-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_auto_20220904_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandetails',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
