# Generated by Django 3.2.6 on 2022-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0006_alter_technicianspecializations_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianspecializations',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='technician.Specialization'),
        ),
    ]
