# Generated by Django 3.2.6 on 2022-09-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0007_alter_technicianspecializations_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciandetails',
            name='skill_badge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.skillbadge'),
        ),
        migrations.DeleteModel(
            name='TechnicianBadge',
        ),
    ]
